FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY {template_root_dir} /app/training-template
RUN pip install /app/training-template

COPY {training_plan_name}/data /app/{training_plan_name}/data
COPY {training_plan_name}/profiles /app/{training_plan_name}/profiles
COPY {training_plan_name}/steps /app/{training_plan_name}/steps
COPY {training_plan_name}/recipe.yaml /app/{training_plan_name}/recipe.yaml

WORKDIR /app/{training_plan_name}

CMD ["training-template", "run", "--profile", "local"]
