FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY {template_root_dir} /app/training-plan-template
RUN pip install /app/training-plan-template

COPY {training_plan_name}/data /app/{training_plan_name}/data
COPY {training_plan_name}/profiles /app/{training_plan_name}/profiles
COPY {training_plan_name}/steps /app/{training_plan_name}/steps
COPY {training_plan_name}/recipe.yaml /app/{training_plan_name}/recipe.yaml

WORKDIR /app/{training_plan_name}

RUN chmod -R 777 /app/{training_plan_name}/metadata/mlflow

CMD ["training-plan-template", "run", "--profile", "local"]
